### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by wlcx** [YSTV/SMS#1]
![giphy](https://user-images.githubusercontent.com/3065381/48132379-39a13d80-e28b-11e8-95eb-554774c803cd.gif)

**Comment by nerdopoly** [comment]
more like rewrite in no.

**Comment by nerdopoly** [comment]
i'm listening 🤔

**Comment by wlcx** [comment]
![image](https://user-images.githubusercontent.com/3065381/48132785-994c1880-e28c-11e8-9562-e7de040369e4.png)
